import module
=============
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

instantiation
=============
>>> bg = BaseGeometry()
>>> isinstance(bg, BaseGeometry)
True

test bg.area(self)
==================
>>> "area" in dir(bg)
True
>>> bg.area()
Traceback (most recent call last):
	...
Exception: area() is not implemented


test bg.integer_validator(self, name, value)
=============================================
>>> "integer_validator" in dir(bg)
True
>>> bg.integer_validator("a", -1)
Traceback (most recent call last):
	...
ValueError: a must be greater than 0

>>> bg.integer_validator("a", 0)
Traceback (innermost last):
	...
ValueError: a must be greater than 0

>>> bg.integer_validator("a", "value")
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", 100e100000)
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", False)
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", True)
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", 3.45)
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", 3.0)
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", -3.4)
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", float('inf'))
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", float('-inf'))
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", None)
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator()
Traceback (innermost last):
	...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> bg.integer_validator("a")
Traceback (innermost last):
	...
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator("a", [1, 2])
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", (1, 2))
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", {1, 2})
Traceback (innermost last):
	...
TypeError: a must be an integer

>>> bg.integer_validator("a", 1)
>>> bg.integer_validator("a", 100)
>>> bg.integer_validator("a", 5)
